### ISSUE TITLE
automatisierte Liste: Abreisen Dream Inn

### ISSUE THREAD

**Issue by Anat42** [Space-Eye/serd#104]
betrifft Personen, die im Dream Inn untergebracht sind, in den Gesuchen
täglich morgens eine Liste erstellen mit folgenden Angaben
- wie viele gesamt da sind
- wie viele laut Datenbank an diesem und den Folgetagen abreisen

**Comment by Anat42** [comment]
mit Zimmernummern
und das ganze dann an Mantas schicken. Adresse folgt.

**Comment by Anat42** [comment]
Emailtext:
"Hallo,
Space-Eye hat laut Datenbank gerade [total number] Personen um Dream Inn untergebracht.
Davon reisen heute [Datum des aktuellen Tags] [Zahl der Abreisenden heute] aus den Zimmern [Zimmernummern] ab."
"Am [Datum des Tags] reisen nach derzeitigem Stand [Zahl der Abreisenden an dem Tag] aus den Zimmern [Zimmernummern] ab." Diesen Satz so oft wie nötig wiederholen, für alle Tage, an denen Leute abreisen.
"Herzliche Grüße
**Team Space-Eye**"

**Comment by loreson** [comment]
Ist implementiert, warte noch auf die Adresse

**Comment by Anat42** [comment]
Lohnt sich ja nicht, weil die Leute das nie rechtzeitig eintragen.
