### ISSUE TITLE
Die Formulare sind nicht hübsch

### ISSUE THREAD

**Issue by Anat42** [Space-Eye/serd#19]
![image](https://user-images.githubusercontent.com/103075602/163494216-3cdd5881-e89a-41d7-b7d1-1aff502cbab0.png)

kann der Text auch unter oder über den Auswahlfeldern stehen?

![image](https://user-images.githubusercontent.com/103075602/163494516-788e9892-8899-4724-9757-6f5d947d8d0e.png)
helptext steht unter dem anderen Text, der hilft leider auch nicht. ("innerhalb eines Tages" im unteren Bild)

Auf den Beispielbildern läuft das Formular auf meinem PC, Texte sind daher anders.

**Comment by bengeisler** [comment]
### Position Text / Eingabefelder
Der Text ist responsive, d.h. abhängig von der Bildschirmbreite steht er entweder neben oder über den Eingabefeldern. Das kann ich natürlich anpassen. Dazu bräuchte ich konkrete Angaben, wie es aussehen soll:
- immer über oder unter den Feldern?
- Umschaltung bei unterschiedlichen Bildschirmgrößen? Am Desktop bleibt durch "immer übereinander" viel horizontaler Platz ungenutzt

### Hilfetext
- Der Hilfetext kommt nicht aus der Darstellung, sondern aus den Models selbst. Das müsste jemand anders übernehmen, vielleicht @loreson ?
- Auch hier: wie soll die Darstellung genau aussehen?

### Allgemein
Es ist empfehlenswert, pro _bug_ ein _issue_ zu erstellen und die _issues_ möglichst konkret zu formulieren. Eine gute Einführung findet sich [hier](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f).

**Comment by bengeisler** [comment]
Der Hilfetext wird jetzt als Popup sowohl beim Text als auch beim Eingabefeld angezeigt:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/73435674/163726871-3028d096-305a-4ceb-afc8-1a6541dff086.png">

**Comment by Anat42** [comment]
Mein Problem war, dass das Formular nicht mal die Hälfte der Bildschirmbreite genutzt hat und der Text dadurch in der Vertikalen so viel Platz gebraucht hat.
Ich hab's mir nochmal angesehen und kann mein Problem am PC nicht mehr reproduzieren, also schon bevor du was geändert hast, die Textanordnung passt jetzt so.

Am Handy hab ich das Problem aber noch:
![Screenshot_20220417-202551_Ecosia](https://user-images.githubusercontent.com/103075602/163727855-f5380565-9f5c-459c-9169-28d5d90ce1eb.jpg)

**Comment by bengeisler** [comment]
Ich habe die breakpoints zur Umschaltung des Layouts nochmal angepasst. Jetzt wird früher in die Darstellung übereinander gewechselt.

Am Handy funktioniert es noch nicht, weil der aktuelle Stand des repos nicht auf dem Server läuft. Ich nehme an, dass das aktuell noch manuell hochgeladen wird und wir keine CI/CD pipeline haben.
