### ISSUE TITLE
Angebot: Fehlermeldung Kinder fehlt in Chrome

### ISSUE THREAD

**Issue by Anat42** [Space-Eye/serd#21]
Das "Zahl der KInder"-Feld ist ein Pflichtfeld. Wenn das in Chromium (wie auch immer der browser heißt) frei bleibt, aktiviert es zwar das Feld, aber es kommt keine hübsche rote Fehlermeldung.
Nicht dau-kompatibel.

**Comment by bengeisler** [comment]
Das trifft auf alle Pflichtfelder zu. 

Die `field.errors` bleiben leer - möglicherweise ein bug bei der Validierung?

**Comment by loreson** [comment]
Der Browser schickt das Formular gar nicht ab, wenn Pflichtfelder leer sind, und chromium hat sich entschlossen dann nur den focus auf das Feld zu setzen, anstatt eine Fehlermeldung zu bringen. 
Wenn man nur ein Leerzeichen eingibt kommt eine gut sichtbare Fehlermeldung von Django.
Die Einzige möglichkeit die mir einfällt ist alle Felder als optional deklarieren, und bei der Validierung manuel prüfen

**Comment by bengeisler** [comment]
Mir ist aufgefallen, dass es jetzt geht. Es kommt zwar keine Fehlermeldung, aber ein Tooltip unter dem leeren Feld. Zusammen mit den Sternchen für die erforderlichen Eingaben sollte das reichen. Getestet mit Chrome und Safari.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/73435674/163766217-634baade-cc37-4a54-a3a0-ecc0bced940a.png">
