### ISSUE TITLE
Datumsanzeige in der Tabelle

### ISSUE THREAD

**Issue by Anat42** [Space-Eye/serd#24]
Wenn ein Datum bei ukrainischer oder russischer Spracheinstellung in die Formulare eingegeben wird, wird es in der Tabelle auch auf ukrainisch oder russisch angezeigt.
Kann das Datum in der Tabelle unabhängig von der Eingabesprache auf deutsch wiedergegeben werden?

**Comment by loreson** [comment]
Datumsanzeige hängt von der gewählten Lokalisierung beim Betrachten ab.
