### ISSUE TITLE
Filterfunktion für die Datenbank

### ISSUE THREAD

**Issue by Anat42** [Space-Eye/serd#4]
Filter von bestimmten Spalten.

- bei Gesuchen und Angeboten
- welche genau folgt

**Comment by Anat42** [comment]
Gesuche:
- Name
- Gesamt
- Teilbar
- aktuelle Unterbringung
- Haustiere
- Sprachen
- Barrierefrei
- Priorität
- Status

Angebote:
- Name
- PLZ
- Ort
- Kosten
- spontan
- begrenzt verfügbar
- barrierefrei
- eigene Wohnung
- Haustiere
- Status

**Comment by loreson** [comment]
Implemented in a286f023b6568ff1492a20cd406982649e4eeb6e
