### ISSUE TITLE
Skript Telefonnummern mit 0 am Beginn ergänzen

### ISSUE THREAD

**Issue by Anat42** [Space-Eye/serd#85]
- Durch die Excel-Tabelle sind ja viele Telefonnummern kaputt gegangen, weil die Null am Beginn verschwunden ist.
- Ist es möglich ein Skript zu schreiben, dass bei allen Telefonnummern, die nicht mit '0' oder '+' beginnen, eine '0' davor zu schreiben?
- Das würde das Abspeichern erleichtern und beschleunigen
- bei Angeboten und Gesuchen

**Comment by loreson** [comment]
done
