### ISSUE TITLE
Gesuche: Formular: Punkt einfügen: Raucher

### ISSUE THREAD

**Issue by Anat42** [Space-Eye/serd#89]
Für die Vermittlung ist es praktisch zu wissen, ob die Gäste rauchen.

- [x]  Abfrage in Form einer Checkbox, Text: "Raucht jemand aus Ihrer Gruppe?"

- [ ] Übersetzung

**Comment by loreson** [comment]
Feld ist in #103  implementiert, aber die Übersetzungen sind nur aus google-translate.
