### ISSUE TITLE
Gesuche: eine Gesamtpersonenzahl einfügen

### ISSUE THREAD

**Issue by Anat42** [Space-Eye/serd#9]
bisher gibt es eine Spalte für Erwachsene eine für Kinder. Eine zusätzliche Gesamtanzahl würde den Vergleich mit den Angeboten erleichtern und filtern sinnvoller machen.
Kann man die automatisch zusammenzählen? Menschen können das ja nicht so gut. daher würde ich das ungern ins Formular aufnehmen.

**Comment by loreson** [comment]
Implemented in 7feef4805c10a49166b68c219a453116f75a91ea
